version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env    

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: rbac
      MYSQL_USER: root
      MYSQL_PASSWORD: janak123
      MYSQL_ROOT_PASSWORD: janak123
      MYSQL_ROOT_HOST: 172.19.0.1
    ports:
      - "3306:3306"  
    volumes:
      - ./dbdata:/var/lib/mysql 

  assignment:
    container_name: assignment
    build:
      context: ./
      dockerfile: ./apps/assignment/Dockerfile
    ports:
      - '4000:5000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - consumer
      - mysqldb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev assignment

  consumer:
    container_name: consumer
    build:
      context: ./
      dockerfile: ./apps/consumer/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mysqldb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev consumer  